apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkcrd-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: networkcrd-controller
  template:
    metadata:
      labels:
        app: networkcrd-controller
    spec:
      containers:
        - name: networkcrd
          image: skaffold-custom